### PR TITLE
update packages

### PR DESCRIPTION
**Pull request by tikicoder**
code updates to support package updates

### CODE REVIEW

**Comment by alexwaibel** [comment]
Thank you for submitting this PR. Could you elaborate a bit further on the code changes and why they're necessary to update the vulnerable NPM packages? I agree that it is worth upgrading the packages if we can, it just seems there are many unrelated changes included.

This project also follows the poorly named [JavaScript Standard Style](https://standardjs.com/) and from a quick glance it appears there are some formatting issues with your code that will not pass the CICD. Before this can be merged, these style inconsistencies will need to be addressed.

**Comment by tikicoder** [comment]
I was unaware of the standard. The updates were required after I updated as the code no longer worked for me without modifications. I could have been maybe overzealous but I tried to take out the items I did specifically for my build. I know one of the changes was to support the changes in the API around Recaptcha and support v2 and v3 captcha. I would have to know what changes you are referring to, to comment on why it was done.

**Comment by alexwaibel** [comment]
Closing this as I believe my recent changes in #396 and #397 covered upgrading the key dependencies to their latest version. Feel free to comment here if you think anything was missed and needs addressed.

**Comment by datapolitical** [comment]
I need v3 support @alexwaibel so I would love to see this PR accepted.

**Pull request closed without merging**
