### PR TITLE
#23 - Add labels in the example form (master)

### PR DESCRIPTION
**Pull request by sukiletxe**
This improves the form's accessibility.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
This is great, but to be honest I'd prefer to have the inputs nested inside the labels to get rid of the `id` and `for` attributes. I think this keeps the examples simpler. Do you mind changing that?

Thanks!

**Comment by sukiletxe** [comment]
To be honest I didn't know that approach . I'll change it later.

**Comment by sukiletxe** [comment]
This pr and the other one should be fine now.

**Comment by eduardoboucas** [comment]
Perfect, thanks!

**Pull request merged**
