### PR TITLE
Add support to use user input as git committer

### PR DESCRIPTION
**Pull request by yifanlu**
The following config option enables this

``` yaml
commit:
  name: name # field
  email: email # field
```

The comment commit will use the user inputted name and email.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Thanks for the PR! Can I get your views on the use case for this?

**Comment by yifanlu** [comment]
I'm a bit OCD and don't feel good about the comment commits being made in one name when they are not the same originator of the content. This way, commenters are "contributors" uniquely identified by their name and email (or md5 of email if you use that transform). It also lets you use various git tools and statistics in the command line (quickly find all comments by this user) and if you're using Staticman with your personal github token, I think this doesn't mess with your stats (although I haven't checked).

**Comment by eduardoboucas** [comment]
What would happen if someone got ahold of my e-mail address and used it to submit an entry on someone's blog? Would it be accepted, and would it show in my activity feed and list of commits?

You have a valid point, I'm just trying to make sure we cover all the bases before merging to avoid creating problematic situations.

Thanks!

**Comment by yifanlu** [comment]
I would hope github prevents that since there's nothing stoping such a user from creating a repo and doing that themselves. But again, it's not something I've tested.

**Comment by caspervonb** [comment]
> What would happen if someone got ahold of my e-mail address and used it to submit an entry on someone's blog? Would it be accepted, and would it show in my activity feed and list of commits?

At the very least, it would be linked as being you in the commit logs.

**Comment by eduardoboucas** [comment]
Yeah, I'm torn on this. It seems like opening room for possible abuse, which I really don't want to do.

**Comment by caspervonb** [comment]
One idea I've been thinking about for @postbot is to implement OAuth, which is doable but there are some open questions like, do bearer tokens only get one time use, etc.

**Comment by yifanlu** [comment]
Personally I use the md5 transform so all "emails" are just unique hashes.

**Comment by eduardoboucas** [comment]
> Personally I use the md5 transform so all "emails" are just unique hashes.

My point is that we're telling the platform to commit on behalf of someone else, based on the information sent in those fields. It doesn't really matter how you then store the data on your files, be it with a md5 hash or plain text.

It seems to me that the possible risks of abuse seem too significant when compared to the benefits this would bring.

If someone is able to dedicate some time to thoroughly test this and see what room there is for abuse and suggest any workarounds, I'm happy to reopen the discussion, but for now I'll close the PR, sorry.

Thanks!

**Pull request closed without merging**
