### PR TITLE
Merge repo fixes from dev into master

### PR DESCRIPTION
**Pull request by alexwaibel**
I've just merged #319 into the dev branch and think it would be wise to also merge these fixes into master so that others can more easily begin hosting their own instances.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
It's expected that the Travis builds are still failing, right?

**Review by eduardoboucas — APPROVED** [review]

**Comment by alexwaibel** [comment]
@eduardoboucas yeah, there's still 20 failing test cases but I've been able to manually test GitHub integration both with basic token access and with app auth. In both instances it was able to successfully make a PR on my test repo with my comment. I plan to look into fixing those failing test cases next l, so we could wait for that work to be finished before merging into master, but then master will stay broken for a longer period of time.

**Comment by eduardoboucas** [comment]
@alexwaibel I'm happy for this to be merged into master now, if that's what you want to do. 🙂

**Comment by alexwaibel** [comment]
@eduardoboucas sounds good, I'll go ahead and merge this in. When I get more time I plan to fix those remaining test failures so we can get travis builds back to a passing state.

**Pull request merged**
