### PR TITLE
Notify commenter that their comment was accepted

### PR DESCRIPTION
**Pull request by gabeluci**
This pull request addresses two issues when notifications are enabled:

1. Currently, whether moderation is on or off, a commenter is subscribed to the reply mailing list *before* the notifications are sent out. This means that a commenter gets an email saying "Someone replied to a comment you subscribed to" when really, no one has yet replied to their comment (since it's their own comment that triggered the email). This is confusing to a user.

2. When moderation is enabled, that email referred to in (1.) effectively notifies the commenter that their comment has been approved. It would be nice to keep that idea, but actually say "Your comment has been accepted".

This resolves these issues in the following ways:

### If moderation is disabled

It's simple: the commenter is simply subscribed to the reply mailing list *after* the reply notification email is sent out, rather than before.

### If moderation is enabled

When a comment is submitted, a mailing list is created using the name of the git branch used for the pull request. The only member is the commenter. This will serve as the **_accepted notification mailing list_**.

If the pull request is merged:

1. Email is sent to the **_reply notification mailing list_** (if this was a reply)
2. Email is sent to the **_accepted notification mailing list_** (the one created at the time of submission) using a new email template that says, "Your comment has been accepted".
3. The one member of the **_accepted notification mailing list_** is moved to the **_reply notification mailing list_** (if this is a top-level comment, the **_reply notification mailing list_** is created here)
4. The **_accepted notification mailing list_** is deleted.

If the branch was closed without being merged, then the **_accepted notification mailing list_** is just deleted and no emails are sent.

### Caveat

If the commenter opted-out of reply notifications (i.e. `options.subscribe` is empty), then they will not get the "accepted" notification. I believe this is acceptable since if someone opts out of reply notificaitons, then they likely don't care to see *any* emails from you.

### Testing

This functionality is already enabled on my own site: https://www.gabescode.com. Feel free to add a test comment on any article; just say it's a test comment (unless you actually have a legit comment to make). I'll accept the comment so you can see the email, but later I'll delete the test comments.

### CODE REVIEW

**Comment by OlafHaag** [comment]
Thanks for this. I saw in the code that when the **accepted notification e-mail** is sent there is no unsubscribe link. This is probably because the user isn't yet subscribed to the **reply notification mailing list**. Is there a way to inject an unsubscribe link for the **reply notification mailing list** in that message?
This would be very useful, because [GDPR Art. 7, §3 demands](https://gdpr-info.eu/art-7-gdpr/):
> 1: The data subject shall have the right to withdraw his or her consent **at any time**.
> ...
> 4: It shall be as easy to withdraw as to give consent.

So when the user decides against receiving notification before the next reply is made that shall be possible. This also means that in any case an e-mail notification with unsubscribe link shall be sent after commenting and not having to wait for the next reply to withdraw consent, if there ever is another reply.
This is related to #277.

**Comment by gabeluci** [comment]
@OlafHaag The easiest way is to include a link to unsubscribe from your *entire domain* by putting a link to `%unsubscribe_url%` in your email template. But that means they won't get email for anything on your site, even if they reply to another comment. You can decide if you want to figure out a way to allow them to re-subscribe.

Here is Mailgun's documentation on their unsubscribe links: https://documentation.mailgun.com/en/latest/user_manual.html#tracking-unsubscribes

**Comment by polchky** [comment]
Are there any plans so far to address the two issues presented in this thread ?

**Comment by alexwaibel** [comment]
@polchky this PR is pretty far behind master which I believe is why I originally closed it. If you're facing this issue still, please submit a bug for it under "Issues" so we can keep track of it.

If you or someone else would like to tackle this and submit an up to date PR I'd be happy to review. I unfortunately don't have the bandwidth right now to make this change myself.

**Comment by gabeluci** [comment]
@polchky If you want to use my code, I did update my branch a few months ago to bring it up to date with the current staticman code. You can still use that branch: https://github.com/gabeluci/staticman/tree/accepted-notifications

**Comment by alexwaibel** [comment]
@gabeluci you're welcome to reopen this PR too. The file diff shows a lot of unrelated changes though. Are you sure this branch is up to date?

**Comment by gabeluci** [comment]
Well it was up to date when I last worked on it about 6 months ago, so it's not anymore.

**Comment by polchky** [comment]
@gabeluci @alexwaibel Thank for the info, I might take a shot at this pretty soon.

**Pull request closed without merging**
