### PR TITLE
Added support for user input sanitizing

### PR DESCRIPTION
**Pull request by yifanlu**
Added transformation option to sanitize user input in order to prevent XSS.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Thanks for this! What exactly is the difference between the `sanitize` and `escape` options? And would you want to use only one of them depending on the use case, or would you always require both?

Just trying to understand if the current concept of transforms is capable of handling this properly in the long-term.

**Comment by yifanlu** [comment]
According to the documentation for "sanitize", removed unsafe HTML tags (like script for example) and attributes while allowing safe html tags (like b) and markdown (since it's not html). This would be used for user input to be displayed.

Escape I think is less useful since it turns HTML entities to text `<b>` => `&lt;b&gt;`

**Comment by eduardoboucas** [comment]
I like that, but I wonder if _sanitize_ should be a transform or just enabled for all fields by default. Seems like an important thing to have.

**Comment by yifanlu** [comment]
I guess there might be a use case for submitting fields that are not displayed.

**Comment by eduardoboucas** [comment]
Sorry to be a pain, but do you mind sending this PR to the `dev` branch instead?

**Comment by jayvdb** [comment]
@yifanlu , there are conflicts which have occurred and need to be resolved.

**Comment by eduardoboucas** [comment]
That's fine, I'll solve the conflicts. It's my bad that the PR is sitting here for ages. I've been working on a refactoring that I've just finished, so I'll finally merge this soon. 

Thanks!

**Comment by mrcnski** [comment]
Bump. This functionality would be really useful for me.

Can this PR also update the [transforms](https://staticman.net/docs/configuration#transforms) documentation to include `sanitize`? Not even sure if it's currently up-to-date, the only option I see there is `md5`.

**Comment by matbrgz** [comment]
No news?

**Pull request closed without merging**
